name: Build and Upload Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Space-separated list of packages to build"
        required: true
        default: "PACKAGE_1 PACKAGE_2"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64
          - arm
          - i686
          - x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker build -t my-build-image ./scripts

      - name: Run build-package script inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            my-build-image ./scripts/build-package.sh -a ${{ matrix.arch }} ${{ github.event.inputs.packages }}

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: output-${{ matrix.arch }}
          path: output/
