# .github/workflows/build-packages.yml

name: Build and Upload Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Space-separated list of packages to build"
        required: true
        default: "PACKAGE_1 PACKAGE_2"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64
          - arm
          - i686
          - x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          chmod +x scripts/setup-ubuntu.sh
          ./scripts/setup-ubuntu.sh

      - name: Run build-package script
        run: |
          chmod +x ./build-package.sh
          ./build-package.sh ${{ matrix.arch }} ${{ github.event.inputs.packages }}
        
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: output-${{ matrix.arch }}
          path: output/
