name: Build and Upload Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Space-separated list of packages to build'
        required: true
        default: ''

jobs:
  build:
    timeout-minutes: 480
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, arm, i686, x86_64]

    steps:
      - name: Log input package
        run: |
          echo "Packages to build: ${{ github.event.inputs.packages }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build-package
        run: |
          echo "Starting build for architecture: ${{ matrix.arch }}"
          ./scripts/run-docker.sh ./build-package.sh -a ${{ matrix.arch }} ${{ github.event.inputs.packages }}
          echo "Build completed for architecture: ${{ matrix.arch }}"

      - name: Check output directory
        run: |
          if [ -z "$(ls -A output)" ]; then
            echo "Output directory is empty."
            exit 1
          fi

      - name: Archive output directory
        run: |
          echo "Archiving output directory..."
          tar -czvf output.tar.gz -C output .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-${{ matrix.arch }}
          path: output.tar.gz

