name: Build and Upload Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Space-separated list of packages to build'
        required: true
        default: 'PACKAGE_1 PACKAGE_2'

jobs:
  build:
    timeout-minutes: 480
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, arm, i686, x86_64]

    steps:
      - name: Log input package
        run: echo "Packages to build: ${{ github.event.inputs.packages }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore output cache
        uses: actions/cache@v2
        id: cache-output
        with:
          path: output
          key: output-${{ matrix.arch }}-${{ github.event.inputs.packages }}
          restore-keys: 
            - output-${{ matrix.arch }}

      - name: Log cache status
        run: |
          if [[ ${{ steps.cache-output.outputs.cache-hit }} == 'true' ]]; then
            echo "Cache hit for output directory."
          else
            echo "No cache found, starting fresh."
          fi

      - name: Run build-package
        run: |
          echo "Starting build for architecture: ${{ matrix.arch }}"
          ./scripts/run-docker.sh ./build-package.sh -a ${{ matrix.arch }} ${{ github.event.inputs.packages }}
          echo "Build completed for architecture: ${{ matrix.arch }}"

      - name: Save output cache
        if: success()
        uses: actions/cache@v2
        with:
          path: output
          key: output-${{ matrix.arch }}-${{ github.event.inputs.packages }}

      - name: Archive output directory
        run: tar -czvf output.tar.gz -C output .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output-archive
          path: output.tar.gz
